### ISSUE TITLE
Margins creeping in from ancestors, even when polyfill not needed

### ISSUE THREAD

**Issue by tremby** [gavinmcfarland/flex-gap-polyfill#54]
I've got an element with `display: grid; gap: 4rem;`. It's a grid so it doesn't even need the polyfill but I understand why it applies rules anyway -- the "grid" part may be composed from a different ruleset, and you've no way of knowing.

But I've configured the plugin with `flexGapNotSupported: ".no-flex-gap"`, and that class is not present since I'm testing with a browser which doesn't need the polyfill.

In this scenario I'd expect the polyfill not to apply any rules at all.

But I'm seeing a margin being added to my grid element, via `--orig-margin-top`, of positive 3rem. I see that this variable is being set on a container *multiple levels up* -- it's nothing to do with the container I want to be a grid.

I don't see this scenario mentioned in the readme, but surely it's very common.

Example:

```css
.wrapper {
  margin: 3rem 0;
  border: 1px solid black;
}
.grid {
  display: grid;
  gap: 4rem;
  grid-template-columns: 24rem 1fr;
  border: 1px solid red;
}
```

```html
<div class="wrapper">
  <h2>whatever content</h2>
  <div class="grid">
    <div>cell 1</div>
    <div>cell 2></div>
  </div>
</div>
```

The margin-top of `.wrapper` is being added to the margin-top of `.grid`, even though there should be no margin at all.
